### ISSUE TITLE
[Bug] Can't sync expedition save to Assistant for No Man's Sky app

### ISSUE THREAD

**Issue by Umuthoper** [zencq/NomNom#159]
### Description
When I select an expedition save and click the Assistant for No Man's Sky button the app just crashes

### Reproduce

1. Click on an epedition save
2. Click on Asistant for No Man's Sky

### Expected Behavior
It was supposed to give me a code to sync with Assistant for No Man's Sky

### Files
Couldn't find a way to find and exort a save file.

Crash Report:

NomNom 4.50.1.36-beta.6+d6f809724f0d71d8620ca8909d2b8b1f1bdb5b58 Crash Report

Environment

Operating System
Microsoft Windows 10.0.19045

.NET
.NET 6.0.26

Exception

Type
System.NullReferenceException

Message
Object reference not set to an instance of an object.

Stack Trace
at NomNom.ViewModels.AssistantTransferDialogViewModel.FillInventories()
at NomNom.ViewModels.AssistantTransferDialogViewModel.OnDialogOpened(IDialogParameters parameters)
at Prism.Services.Dialogs.DialogService.<>c__DisplayClass9_0.<ConfigureDialogWindowContent>b__0(IDialogAware d)
at Prism.Common.MvvmHelpers.ViewAndViewModelAction[T](Object view, Action`1 action)
at Prism.Services.Dialogs.DialogService.ConfigureDialogWindowContent(String dialogName, IDialogWindow window, IDialogParameters parameters)
at Prism.Services.Dialogs.DialogService.ShowDialogInternal(String name, IDialogParameters parameters, Action`1 callback, Boolean isModal, String windowName)
at Prism.Services.Dialogs.DialogService.ShowDialog(String name, IDialogParameters parameters, Action`1 callback)
at NomNom.ViewModels.MainWindowViewModel.OpenAssistantTransfer()
at Prism.Commands.DelegateCommand.Execute()
at Prism.Commands.DelegateCommand.Execute(Object parameter)
at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
at System.Windows.Controls.Primitives.ButtonBase.OnClick()
at System.Windows.Controls.Button.OnClick()
at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Additional Context
 
 - Downloaded this from Nexus mods
 - Version: 4.5
 - Platform: The Xbox app on Windows 10

**Comment by cengelha** [comment]
Did you try to open it with a pre-Omega save selected (not saved with Omega+)? I could reproduce it like that

**Comment by Umuthoper** [comment]
> Did you try to open it with a pre-Omega save selected (not saved with Omega+)? I could reproduce it like that

It works normally when I try it with a normal save. It only crashes on Omega saves.
