### ISSUE TITLE
[Bug] Crash when trying to lock all under save data

### ISSUE THREAD

**Issue by JacobZufall** [zencq/NomNom#181]
### Description
When editing save data, if you try to click "Lock All" after pressing "Unlock All", NomNom crashes. The report generates the following information:

NomNom 4.70.2.41-beta.11+363b6488df50cc47d957b37a1d99b612623fac49 Crash Report

**Operating System:** Microsoft Windows 10.0.22631

**.NET:** .NET 6.0.26

**Type:** System.InvalidOperationException

**Message:** Collection was modified; enumeration operation may not execute.

**Stack Trace:** at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
at Newtonsoft.Json.Linq.JsonPath.QueryFilter.ExecuteFilter(JToken root, IEnumerable`1 current, JsonSelectSettings settings)+MoveNext()
at NomNom.Models.ItemWrapper.set_IsSeasonRewardRedeemed(Boolean value)
at NomNom.ViewModels.EditorSaveSynthesisViewModel.ModifyCollection(String grid, IList collection, Boolean value)
at NomNom.ViewModels.EditorAccountViewModelsBase.LockAll(DataGrid parameter)
at Prism.Commands.DelegateCommand`1.Execute(T parameter)
at Prism.Commands.DelegateCommand`1.Execute(Object parameter)
at Prism.Commands.DelegateCommandBase.System.Windows.Input.ICommand.Execute(Object parameter)
at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
at System.Windows.Controls.Primitives.ButtonBase.OnClick()
at System.Windows.Controls.Button.OnClick()
at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Reproduce
1. Load save
2. Edit save data
3. Unlock all on something such as expedition rewards
4. Relock everything to witness crash

### Expected Behavior
It should re-lock everything like it does in account data, except account data doesn't save.

**Comment by Snoddas76** [comment]
I'm getting the same issue using the latest NomNom.

**Comment by peter-tornqvist-kan** [comment]
Same here latest as of today (4.70.3.42-beta.12+b57221a3f961ecade8abf85512fb605cb0e6e6f9), seems to work when clicking "Lock all" on "Create exotic items from Quicksilver" though
